# Generated by Django 4.2.25 on 2025-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
