# Generated by Django 4.2.25 on 2025-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_task_due_date_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
        ),
    ]
